name: xeus-cpp
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq<4.0
  - nlohmann_json
  - nlohmann_json-abi
  - CppInterOp>1.7.0
  - pugixml
  - cpp-argparse
  - llvm-openmp
  # Test dependencies
  - pytest
  - jupyter_kernel_test<0.8
  - papermill
  - nbformat
  - nbval
  - pytest-rerunfailures
  - doctest
