name: xeus-cpp-2
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler=1.7.0
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq<4.0
  - nlohmann_json=3.12.0
  - CppInterOp
  - pugixml
  - cpp-argparse>=3.0,<4.0
  # Test dependencies
  - pytest
  - jupyter_kernel_test<0.8
  - papermill
  - nbformat
  - nbval
  - pytest-rerunfailures
  - doctest
