name: xeus-cpp
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - make
  - cmake
  - cxx-compiler
  # Host dependencies
  - xeus>=5.0.0
  - xeus-zmq<4.0
  - nlohmann_json
  - nlohmann_json-abi
  - CppInterOp>=1.8
  - pugixml
  - cpp-argparse
  # Test dependencies
  - pytest
  - jupyter_kernel_test<0.8
  - papermill
  - nbformat
  - nbval
  - pytest-rerunfailures
  - doctest
