name: xeus-cpp-wasm-host
channels:
  - https://repo.mamba.pm/emscripten-forge
  - https://repo.mamba.pm/conda-forge
dependencies:
  - emscripten-abi==3.1.73
  - nlohmann_json
  - xeus-lite
  - xeus
  - CppInterOp>=1.5.0
  - cpp-argparse
  - pugixml
