name: xeus-cpp-wasm-host
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.mamba.pm/conda-forge
dependencies:
  - nlohmann_json
  - xeus-lite
  - xeus
  - CppInterOp
  - cpp-argparse
  - pugixml
  - doctest
